#!/usr/bin/env ruby
#
# htmlign - ignore-tester
#
# Copyright (C) 2003 Tanaka Akira  <akr@fsij.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

$KCODE = 'e'

require 'htree'
require 'tempfile'

def path2pattern(*paths)
  /\A#{Regexp.alt *paths.map {|path|
    Regexp.new(path.gsub(%r{[^/]+}) {|step|
      if /\[(\d+)\]\z/ =~ step
        n = $1.to_i
        if $1.to_i == 1
          Regexp.quote($`) + "(?:\\[#{n}\\])?"
        else
          Regexp.quote(step)
        end
      else
        Regexp.quote(step) + '(\[\d+\])?'
      end
    }.gsub(%r{//+}) {
      "/(?:[^/]+/)*"
    })
  }}\z/
end

filename1, *ignore_path = ARGV

ignore_path.each {|path| puts path }

tree1 = HTree.parse(File.read(filename1).decode_charset_guess)

ignore_pattern = path2pattern(*ignore_path)
p ignore_pattern

pred = lambda {|e, path|
  p path if ignore_pattern === path
  not (
    #(HTree::Elem === e && (e.tagname == 'style' ||
    #                       e.tagname == 'script')) ||
    ignore_pattern === path
  )
}

tree2 = tree1.filter_with_path(&pred)

tf1 = Tempfile.new('htmldiff1')
PP.pp(tree1, tf1)
tf1.close

tf2 = Tempfile.new('htmldiff2')
PP.pp(tree2, tf2)
tf2.close

system("diff -u #{tf1.path} #{tf2.path}")
