#!/usr/bin/env ruby

require 'rbconfig'
require 'optparse'

def expand_require(out, filename, dirs, main, included={})
  open(filename) {|f|
    comment = false
    test = false
    f.each {|line|
      if /^=begin/ =~ line
        comment = true
	out.print line
      elsif /^=end/ =~ line
        comment = false
	out.print line
      elsif comment
	out.print line
      elsif !main && (/^if __FILE__ == \$0/ =~ line || /^if \$0 == __FILE__/ =~ line)
        test = true
	out.print "#", line
      elsif test && /^end/ =~ line
        test = false
	out.print "#", line
      elsif test
	out.print "#", line
      elsif /^\s*require '([^']*)'/ =~ line && %r{^/} !~ (req = $1)
	if included[req]
	  out.print "#", line
	else
	  dir = dirs.find {|d| FileTest.exist? "#{d}/#{req}.rb"}
	  if dir
	    out.print "#", line
	    filename = "#{dir}/#{req}.rb"
	    included[req] = filename
	    endmark = 'End_' + [req].pack("m*").delete("\n")
	    #out.print "eval <<'#{endmark}', TOPLEVEL_BINDING, #{"[#{filename}]".dump}, #{out.output_line+1}\n"
	    expand_require(out, filename, dirs, false, included)
	    #out.print "#{endmark}\n"
	  else
	    out.print line
	  end
	end
      else
	out.print line
      end
    }
  }
end

module CountOutputLine
  def output_line
    @output_line = 1 unless defined? @output_line
    @output_line
  end

  def write(str)
    @output_line = output_line + str.count("\n")
    super
  end
end

def parse_options
  $output_filename = nil
  $dep_output_filename = nil
  ARGV.options {|q|
    q.banner = 'rb-link [opts] script-file [library-directories...]'
    q.def_option('--help', 'show this message') {puts q; exit(0)}
    q.def_option('--output=filename', '-o', 'specify output file') {|filename| $output_filename = filename}
    q.def_option('--dependency=filename', '-d', 'specify dependency output file') {|filename| $dep_output_filename = filename}
    q.parse!
  }
end

def open_output
  if $output_filename
    File.open($output_filename, 'w') {|f|
      yield f
      f.chmod 0755
    }
  else
    yield STDOUT
  end
end

def main
  parse_options

  script = ARGV.shift
  libdirs = ARGV
  libdirs = ['.'] if libdirs.empty?

  open_output {|out|
    out.extend CountOutputLine
    interpreter_path = File.join(Config::CONFIG["bindir"], Config::CONFIG["ruby_install_name"])
    out.print "#! #{interpreter_path}\n"
    included = {}
    expand_require(out, script, libdirs, true, included)
    if $dep_output_filename
      open($dep_output_filename, 'w') {|f|
        f.puts "#{$output_filename} : #{included.values.sort.join(' ')}"
      }
    end
  }
end

main
